mqtt:
  client-id: "df3abe82-07eb-469e-b345-d0219a950ada"
  connection:
    broker-adress: "4757e0b60f564e78900a097c3086a003.s1.eu.hivemq.cloud"
    port: 8883
    topic: "todoapp/elements"
    qos: 1
  user:
    username: "testtest"
    password: "Test1234"