mqtt:
  client-id: 703601b0-cc92-4826-b06a-2fe3d034b502
  connection:
    broker-adress: 4757e0b60f564e78900a097c3086a003.s1.eu.hivemq.cloud
    port: 8883
    qos: 1
    topic: todoapp/tasks
  user:
    password: Test1234
    username: testtest
