mqtt:
  client-id: "e4947a81-dbc2-40de-aad8-0dd3eab591f0"
  connection:
    broker-adress: "4757e0b60f564e78900a097c3086a003.s1.eu.hivemq.cloud"
    port: 8883
    topic: "todoapp/tasks"
    qos: 1
  user:
    username: "testtest"
    password: "Test1234"